### ISSUE TITLE
Merlin mipsel build

### ISSUE THREAD

**Issue by happy201807** [Acris/docker-asuswrt-merlin-build#2]
您好 请问https://github.com/MerlinRdev/ac85p-merlin/ 装这个之后 如何才能更新二进制文件？构建merlin环境怎么搭？能否合并进这个project？

**Comment by Acris** [comment]
没太明白你说的更新二进制文件是什么意思，能否说详细一点？

**Comment by happy201807** [comment]
您好，最近换掉R6300v2 入手了redmi AC2100（RM2100），这货是mt7621，看到大家有用之前的Merlin mipsel适配此型号，也就是这个包含软件中心的project MerlinRdev/ac85p-merlin/ ，但是对应的shadowsocks插件已经于两年前停止维护，所以啦还得像之前一样自己维护shadowsocks-libev的二进制文件，也就是您的这个project编译环境，唯独缺少mtk的环境，请问是否可以加进来？

**Comment by Acris** [comment]
此构建环境基于 https://github.com/RMerl/am-toolchains ，暂不支持mipsel架构。

**Comment by happy201807** [comment]
您好，原作者提供了mipsel架构的SDK，请问除了替换SDK 还需要修改docker和脚本的哪些地方来完成编译更新二进制?
